-- nvim_buf_get_name({buffer})
-- vim.fs.dir    
-- vim.uv.fs_stat
-- nvim_win_set_var({window}, {name}, {value})
-- vim.api.nvim_create_user_command(
--   'Fexp',
--   function(opts)
--     local cwd = vim.fs.dirname(vim.api.nvim_buf_get_name(0))
--
--     local entries = {}
--     for name, type in vim.fs.dir(cwd) do
--       if type == "file" or type == "dir" then
--         vim.list_extend(entries, { name })
--       end
--     end
--
--
--     local bufno = vim.api.nvim_create_buf(false, false)
--     if bufno == 0 then
--       vim.notify('Failed to create buffer for Fexp', vim.log.levels.ERROR)
--       return
--     end
--     local winno = vim.api.nvim_open_win(bufno, false, {
--       relative='editor',
--       row=0,
--       col=0,
--       width=50,
--       height=50,
--       focusable=false,
--       style='minimal',
--       zindex=75
--     })
--     if winno == 0 then
--       vim.notify('Failed to create window for Fexp', vim.log.levels.ERROR)
--       return
--     end
--
--     vim.api.nvim_set_current_win(winno)
--     vim.api.nvim_win_set_var(0, 'winfixbuf', true)
--     vim.api.nvim_buf_set_lines(bufno, 0, 0, false, entries)
--   end, {}
-- )

